<?php
$users = [
    [
        'lastname'=>'Ladmin',
        'name'=>'Jean',
        'pseudo'=>'jeanjean',
        'email'=>'jladmin@gmail.com',
        'status'=>'administrateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Legameur',
        'name'=>'Aristide',
        'pseudo'=>'GG34',
        'email'=>'Aristid.goat@gmail.com',
        'status'=>'joueur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
];
?>