<?php
$users = [
    [
        'id'=>'1',
        'lastname'=>'1Ladmin',
        'name'=>'Jean',
        'pseudo'=>'jeanjean',
        'email'=>'jladmin@gmail.com',
        'status'=>'administrateur'
    ],
    [
        'id'=>'2',
        'lastname'=>'2Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'3',
        'lastname'=>'3Legameur',
        'name'=>'Aristide',
        'pseudo'=>'GG34',
        'email'=>'Aristid.goat@gmail.com',
        'status'=>'joueur'
    ],
    [
        'id'=>'4',
        'lastname'=>'4Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'5',
        'lastname'=>'5Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'6',
        'lastname'=>'6Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'7',
        'lastname'=>'7Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'8',
        'lastname'=>'8Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'9',
        'lastname'=>'9Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'10',
        'lastname'=>'10Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'11',
        'lastname'=>'11Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'12',
        'lastname'=>'12Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'13',
        'lastname'=>'13Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'14',
        'lastname'=>'14Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'15',
        'lastname'=>'15Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'16',
        'lastname'=>'16Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'17',
        'lastname'=>'17Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'18',
        'lastname'=>'18Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'19',
        'lastname'=>'19Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'20',
        'lastname'=>'20Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'21',
        'lastname'=>'21Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'22',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'23',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'24',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'25',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'26',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'27',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'28',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'29',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'30',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'31',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'32',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'33',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'34',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'35',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'36',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'37',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'38',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'39',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'40',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'41',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'42',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'43',
        'lastname'=>'M\'Bappe',
        'name'=>'Kylian',
        'pseudo'=>'kyky07',
        'email'=>'K.mbappe@gmail.com',
        'status'=>'joueur'
    ],
    [
        'id'=>'44',
        'lastname'=>'Sissi',
        'name'=>'Princesse',
        'pseudo'=>'Sissi_du_93',
        'email'=>'P.sissi@gmail.com',
        'status'=>'joueur'
    ],
    [
        'id'=>'45',
        'lastname'=>'Sawyer',
        'name'=>'Tom',
        'pseudo'=>'tomtom',
        'email'=>'tSawyer@gmail.com',
        'status'=>'joueur'
    ],
    [
        'id'=>'46',
        'lastname'=>'Coffee',
        'name'=>'john',
        'pseudo'=>'cofcof',
        'email'=>'j.coffee@gmail.com',
        'status'=>'joueur'
    ],
];

$totalUsers=count($users);    // On compte le nombre d'utilisateurs total

// On compte le nombre d'admin, de modérateur et de joueurs . source : https://stackoverflow.com/a/53308963
$totalAdmin = array_count_values(array_column($users, 'status'))['administrateur'];
$totalMod = array_count_values(array_column($users, 'status'))['modérateur'];
$totalGamer = array_count_values(array_column($users, 'status'))['joueur'];
?>