<?php
$users = [
    [
        'id'=>'1',
        'lastname'=>'Ladmin',
        'name'=>'Jean',
        'pseudo'=>'jeanjean',
        'email'=>'jladmin@gmail.com',
        'status'=>'administrateur',
        'pwd'=>'1'
    ],
    [
        'id'=>'2',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'2'
        
    ],
    [
        'id'=>'3',
        'lastname'=>'Legameur',
        'name'=>'Aristide',
        'pseudo'=>'GG34',
        'email'=>'Aristid.goat@gmail.com',
        'status'=>'joueur',
        'pwd'=>'3'
    ],
    [
        'id'=>'4',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'4'
    ],
    [
        'id'=>'5',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'5'
    ],
    [
        'id'=>'6',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'6'
    ],
    [
        'id'=>'7',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'7'
    ],
    [
        'id'=>'8',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'8'
    ],
    [
        'id'=>'9',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'9'
    ],
    [
        'id'=>'10',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'10'
    ],
    [
        'id'=>'11',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'11'
    ],
    [
        'id'=>'12',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'12'
    ],
    [
        'id'=>'13',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'13'
    ],
    [
        'id'=>'14',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'14'
    ],
    [
        'id'=>'15',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'15'
    ],
    [
        'id'=>'16',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'16'
    ],
    [
        'id'=>'17',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'17'
    ],
    [
        'id'=>'18',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'18'
    ],
    [
        'id'=>'19',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'19'
    ],
    [
        'id'=>'20',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'20'
    ],
    [
        'id'=>'21',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'21'
    ],
    [
        'id'=>'22',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'22'
    ],
    [
        'id'=>'23',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'23'
    ],
    [
        'id'=>'24',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'24'
    ],
    [
        'id'=>'25',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur',
        'pwd'=>'25'
    ],
    [
        'id'=>'26',
        'lastname'=>'Lemodo',
        'name'=>'Luc',
        'pseudo'=>'lulu',
        'email'=>'luc.lemodo@gmail.com',
        'status'=>'modérateur'
    ],
    [
        'id'=>'27',
        'lastname'=>'M\'Bappe',
        'name'=>'Kylian',
        'pseudo'=>'kyky07',
        'email'=>'K.mbappe@gmail.com',
        'status'=>'joueur',
        'pwd'=>'27'
    ],
    [
        'id'=>'28',
        'lastname'=>'Sissi',
        'name'=>'Princesse',
        'pseudo'=>'Sissi_du_93',
        'email'=>'P.sissi@gmail.com',
        'status'=>'joueur',
        'pwd'=>'28'
    ],
    [
        'id'=>'29',
        'lastname'=>'Sawyer',
        'name'=>'Tom',
        'pseudo'=>'tomtom',
        'email'=>'tSawyer@gmail.com',
        'status'=>'joueur',
        'pwd'=>'29'
    ],
    [
        'id'=>'30',
        'lastname'=>'Coffee',
        'name'=>'john',
        'pseudo'=>'cofcof',
        'email'=>'j.coffee@gmail.com',
        'status'=>'joueur',
        'pwd'=>'30'
    ],
    [
        'id'=>'31',
        'lastname'=>'Coffee',
        'name'=>'john',
        'pseudo'=>'cofcof',
        'email'=>'j.coffee@gmail.com',
        'status'=>'joueur',
        'pwd'=>'31'
    ],
];

$totalUsers=count($users);    // On compte le nombre d'utilisateurs total

// On compte le nombre d'admin, de modérateur et de joueurs . source : https://stackoverflow.com/a/53308963
$totalAdmin = array_count_values(array_column($users, 'status'))['administrateur'];
$totalMod = array_count_values(array_column($users, 'status'))['modérateur'];
$totalGamer = array_count_values(array_column($users, 'status'))['joueur'];
?>